package fs19.java.backend.presentation.shared.status;

import lombok.Getter;

/**
 * These statuses can use only internal usages, and when it passes to end user please convert it into global status
 */
@Getter
public enum ResponseStatus {

    //success status
    PENDING_PROCESS(0),
    SUCCESSFULLY_SAVED(1),
    SUCCESSFULLY_DELETED(2),
    SUCCESSFULLY_FOUND(3),
    SUCCESSFULLY_CREATED(4),
    SUCCESSFULLY_UPDATED(5),
    //Error status
    INVALID_INFORMATION(-1000),
    DELETE_REQUEST_FAILED(-1001),
    ROLE_NAME_NOT_FOUND(-1002),
    ROLE_ID_NOT_FOUND(-1003),
    INVALID_INFORMATION_ROLE_DETAILS_NOT_FOUND(-1004),
    RECORD_ALREADY_CREATED(-1005),
    PERMISSION_NAME_NOT_FOUND(-1006),
    INVALID_INFORMATION_PERMISSION_DETAILS_NOT_FOUND(-1007),
    PERMISSION_ID_NOT_FOUND(-1008),
    ROLE_RESULT_NOT_FOUND(-1009),
    PERMISSION_RESULT_NOT_FOUND(-1010),
    ROLE_PERMISSION_RESULT_NOT_FOUND(-1011),
    ROLE_PERMISSION_ID_NOT_FOUND(-1012),
    ROLE_PERMISSION_ID_RECORD_ALREADY_EXIST(-1013),
    INVALID_INFORMATION_ROLE_PERMISSION_DETAILS_NOT_FOUND(-1014),
    TASK_NAME_NOT_FOUND(-1015),
    TASK_LEVEL_CREATED_USER_NOT_FOUND(-1016),
    TASK_LEVEL_ASSIGNED_USER_NOT_FOUND(-1017),
    TASK_ID_NOT_FOUND(-1018),
    INVALID_INFORMATION_TASK_DETAILS_NOT_FOUND(-1019),
    INVITATION_EMAIL_NOT_FOUND(-1020),
    INVITATION_ROLE_ID_NOT_FOUND(-1021),
    INVITATION_ROLE_NOT_FOUND(-1022),
    INVITATION_COMPANY_NOT_FOUND(-1023),
    INVALID_INFORMATION_INVITATION_DETAILS_NOT_CREATED(-1024),
    INVITATION_WORKSPACE_ID_NOT_FOUND(-1025),
    INVITATION_ID_NOT_FOUND(-1026),
    INVALID_INFORMATION_INVITATION_DETAILS_NOT_DELETED(-1025),
    INVALID_INFORMATION_INVITATION_DETAILS_NOT_FOUND(-1026),
    COMPANY_ID_NOT_FOUND(-1027),
    COMPANY_NAME_NOT_FOUND(-1028),
    USER_ID_NOT_FOUND(-1029),
    PROJECT_ID_NOT_FOUND(-1030),
    INVITATION_ALREADY_ACCEPTED(-1031);

    final private int status;

    ResponseStatus(int status) {
        this.status = status;
    }
}

